# Generated by Django 3.2.4 on 2021-12-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='slug',
        ),
    ]
